### ISSUE TITLE
Delete associated file of a deleted solution file object

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#160]
When a TaskSolutionFile model is deleted, associated files are [not automatically deleted by Django](https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.fields.files.FieldFile.delete). This could be solved by a management command or a [post_delete signal](https://docs.djangoproject.com/en/1.9/ref/signals/#post-delete).

**Comment by martinmo** [comment]
Another option would be to document the following: using `django-admin unreferenced_files | xargs rm` inside a cronjob (with the management command coming from the django-extensions app) .

**Comment by PhilippMatthes** [comment]
Fixed in pull request #225 by commit [155ede2](https://github.com/st-tu-dresden/inloop/pull/225/commits/155ede27276d54c89f7bcdf9d1071d53a3477813) since it was also associated to a problem creating testing solution files.
