### ISSUE TITLE
Provide an example tasks repository

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#163]
For documentation, (integration) testing and demo purposes, we need a simple tasks repository. Requirements:

* Name: inloop-sample-tasks
* Part of the st-tu-dresden organization
* License: GPLv3 (the same as INLOOP)
* 3 very minimal tasks and accompanying unit tests

I've already created https://github.com/st-tu-dresden/inloop-sample-tasks as a starter package :-)

**Comment by dmuhs** [comment]
Maybe @glmax und @freeDom- can give an opinion on that matter to provide some boilerplate tasks that can also be used for a better testing setting (a public repo that can also be used for GitHub integration tests). Any ideas on that @martinmo?

**Comment by martinmo** [comment]
Yep, I think at least two public Github repos would be ideal. The second one could showcase another language than Java.

**Comment by freakyblue** [comment]
I don't get the idea. What's the difference between these sample-tasks and those which are already in [inloop-tasks](https://github.com/st-tu-dresden/inloop-tasks)?

**Comment by dmuhs** [comment]
The `inloop-tasks` repository also contains the solutions that are used to compile the unit tests. They shouldn't be public to not make it too easy for our students. For new developers and potential other users of the Inloop system it should be possible however, to test the task import functionality and concrete task runs with a set of public sample repository.

**Comment by freakyblue** [comment]
Ah ok, that makes sense. Thank you.

**Comment by martinmo** [comment]
See https://github.com/st-tu-dresden/inloop-java-repository-example.
