### ISSUE TITLE
Download uploaded files as a ZIP archive

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#186]

**Comment by PhilippMatthes** [comment]
@martinmo what do you think, should we generate the zip files on-the-fly? Or should the zip files be stored into the model?

**Comment by martinmo** [comment]
Actually, both. And keep in mind, zipping is a potentially long-running operation and therefore should be done as a background job.

I imagine the sequence as follows:

1. User requests the zip file.
2. If it already exists, just return it.
3. Otherwise, start a background job that creates the zip and tell the user to come back later. As a convenience, the page could refresh the availabilty info automatically. (This is what the solution submit already does.)
4. The background job stores the zip in the model in case it is requested again.
