### ISSUE TITLE
Support tables in Markdown task descriptions

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#187]

**Comment by freakyblue** [comment]
What's the name of the markdown-tool that's used at the moment?

**Comment by martinmo** [comment]
We use the `Markdown` package (https://pypi.python.org/pypi/Markdown). It seems like it provides an extension for tables which must be enabled in the configuration (see http://pythonhosted.org/Markdown/extensions/index.html).

We already have enabled some of the extensions, see https://github.com/st-tu-dresden/inloop/blob/master/inloop/common/templatetags/markdown.py.

In general, you can look up the libraries we use in our `requirements/*.txt` files and use the search functionality on [PyPI](https://pypi.python.org) or the new [PyPI warehouse](https://pypi.org/search/).
