### ISSUE TITLE
Missing <title> tags on several pages

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#189]

**Comment by freakyblue** [comment]
I just noticed one missing in the [solution_detail](https://github.com/st-tu-dresden/inloop/blob/master/inloop/solutions/templates/solutions/solution_detail.html)-template (solved [here](https://github.com/st-tu-dresden/inloop/commit/8e8b123eafc7e4cfbeef01aa1c5f7c4f2a41c54b)). Are there any more?
