### ISSUE TITLE
Work around 404 errors caused by activation links without trailing slashes

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#210]
Apparently, some email clients strip of the trailing slash of the activation link that is sent via email. Of course, this is not our fault, but we can nevertheless be clever and detect such cases.

**Comment by PhilippMatthes** [comment]
@martinmo I changed the option `APPEND_SLASH` to `True` and tested if everything was working fine. As far as I can tell, clicking through all pages, uploading files and viewing test results works perfectly fine. I did not experience any issue with this parameter set to `True`. I therefore opened the Pull Request #218. Closing this issue.
