### ISSUE TITLE
Build stderr and stdout shouldn't be separated

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#236]
At the moment, stderr and stdout are captured separately and displayed in two distinct `<pre>` tags.

![ohne titel](https://user-images.githubusercontent.com/1561982/43328822-52fee4c0-91bf-11e8-935a-d50574eb088d.png)

**Comment by PhilippMatthes** [comment]
@martinmo do you have an example how the real output looks like? Except from the whitespace formatting, should it be 
```
std-err
std-out
``` 
or 
```
std-out
std-err
```
? I will address this tomorrow morning.

**Comment by martinmo** [comment]
The problem is that the output should have never been split in the first place, in the testrunner. In reality, the streams can be interleaved.

**Comment by PhilippMatthes** [comment]
I will start a PR in a few minutes, where we should discuss this more.

**Comment by martinmo** [comment]
I've moved the formatting part into its own issue #340.
