### ISSUE TITLE
Finish the plagiarism user interface

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#243]
The results of the plagiarism check should be easy to download as a spreadsheet (the most straightforward way is to use the existing CSV export of the management command).

**Comment by PhilippMatthes** [comment]
AFAIK, this issue has been closed by this commit: https://github.com/st-tu-dresden/inloop/commit/2284116ce8faa7818527bca0a722d01cb6f8740d
The plagiarism check can be downloaded via the admin GUI. The downloaded zip then contains the needed data.
