### ISSUE TITLE
Improve the test coverage of the grading module

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#244]
The grading module, along with its plagiarism checker, should be more thoroughly tested.

- [x] Test scenarios involving multiple users with each multiple solutions, at different similarity levels
- [x] Is plagiarism correctly detected?
- [x] Are the bonus points calculated correctly?
- [x] Does the exported CSV file contain the correct number of bonus points?
- [x] Corner cases and loopholes:
  - [x] Is date range of the solutions honored in the bonus point calculation?
  - [x] Is the `veto` field honored?
- [x] Check if:
  - [x] Only passed solutions should be considered.
  - [x] Only the most recent passed solution should be considered. 
  - [x] Only the last `PlagiarismTest` is relevant for bonus point calculation.

etc.

**Comment by PhilippMatthes** [comment]
I changed the initial comment to use it as my personal check list on this issue. See this branch: https://github.com/st-tu-dresden/inloop/tree/244-improve-grading-test-coverage

**Comment by martinmo** [comment]
Closed in e55ab379bef2ad81bf8409aad9ae4c4eaa7c37bd.
