### ISSUE TITLE
Automated end-to-end test of a fully configured system (integration test)

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#245]
I usually perform some quick *manual* tests when I deploy INLOOP to production (or perform some updates), in order to validate if all the components (nginx, database, gunicorn, background queue, docker, git) still work together as intented. For example:

* Is static and dynamic media displayed correctly?
* Does the solution upload work?
* Do invalid solutions fail, do valid solutions succeed?
* (Applicable in the future: can ZIPs be downloaded?)

This should be automated as much as possible.

**Comment by PhilippMatthes** [comment]
[SimpleTestCase.assertTemplateUsed](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#default-test-client) could be useful here.

**Comment by PhilippMatthes** [comment]
From the [docs](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#liveservertestcase):

`LiveServerTestCase` could be useful for realtime user action simulation and checking dynamic contents loaded by JavaScript, such as the code editor. This would require the Python library `Selenium`. I personally have mixed feelings with this library, as it comes with lots of compatibility problems, especially on Raspbian based systems (which could be a use case for our system in my opinion). 
Should we use `LiveServerTestCase` or stick to the default dummy client of `SimpleTestCase` @martinmo ?

**Comment by martinmo** [comment]
The simple tests I listed above would be enough and do not require Selenium or any JavaScript. Using Python `requests` library or even a bash script with some `curl` requests should suffice.
