### ISSUE TITLE
Support SAML (aka Shibboleth) authentication

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#251]

**Comment by PhilippMatthes** [comment]
This lib could be useful here:
https://github.com/onelogin/python3-saml

**Comment by martinmo** [comment]
Yes, and [django-mellon](https://pypi.org/project/django-mellon/), which is my current favorite. But in general I dislike that we need to support this complex protocol. All SAML implementations I know of were plagued by serious security issues and I'm sure there are more things coming. Just reading the [warning section in the python3-saml README](https://github.com/onelogin/python3-saml/tree/da5f678d19076486963b3e726e9ed0d787ff39a4#warning) makes me nervous... or [this one here](https://www.cvedetails.com/vulnerability-list.php?vendor_id=11435) or [this one](https://security-tracker.debian.org/tracker/source-package/xmlsec1).
