### ISSUE TITLE
Create the solution editor tab

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#264]
@PhilippMatthes Please prepare the new solution editor tab based on the mockup we discussed. We will strictly separate Javascript code and JSON data. I will take care of implementing the backend REST controllers for saving/retrieving files in another branch.

Notes:
* No inline Javascript, please. Create a new `editor.js` (or whatever name you prefer) in `assets/js`.
* Configuration (if any) will be made available as part of the HTML via a `<script type="application/json" id="config">...</script>` tag so we don't need to hardcode anything.
* calculate the hash SHA1 with Rusha 
  * please don't use `npm` or `bower`, just use the latest release from GitHub (https://github.com/srijs/rusha/releases)
  * the library is standalone an has no other dependencies, can be put under `assets/js`
  * load via `<script src="path/to/rusha.min.js">`, once loaded the class is available as `window.Rusha`

Any questions?

**Comment by PhilippMatthes** [comment]
No questions so far, here is the mockup we discussed:

![mockup-inloop](https://user-images.githubusercontent.com/27271818/49287220-f195c500-f49c-11e8-9e63-8ed4dfb9bed9.jpg)

**Comment by martinmo** [comment]
And an example JSON object that the frontend needs to work with (as we discussed):

```json
{
  "last_submission": "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33",
  "saved_files": {
    "test.java": "public class test {}\n",
    "test2.java": ""
  }
}
```

**Comment by PhilippMatthes** [comment]
@martinmo I just found out that ACE.js also has an autocomplete function that we could use. And, as far as I tested, it supports all kinds of languages, like *Swift*:

<img width="1552" alt="bildschirmfoto 2018-11-30 um 20 28 18" src="https://user-images.githubusercontent.com/27271818/49310476-b4522700-f4de-11e8-928d-a5c6b4f009cd.png">

See the autocompletion demo under https://ace.c9.io/demo/autocompletion.html

**Comment by PhilippMatthes** [comment]
@martinmo, here is a sneak-preview on the current version of the editor. I added `ace.js` with java code highlighting, `ace.js` code completion and a custom design fitting our modern INLOOP-design.

Keep in mind that this is far from finished and needs many more improvements and changes.

<img width="1552" alt="bildschirmfoto 2018-12-03 um 18 17 05" src="https://user-images.githubusercontent.com/27271818/49389933-d7234c00-f727-11e8-95e5-153a4d1ec66c.png">

**Comment by PhilippMatthes** [comment]
@martinmo, here is a sneak-preview on the current version of the editor (with some code of my Java library [jVVO](https://github.com/PhilippMatthes/jVVO)). I added ace.js with java code highlighting, ace.js code completion and a custom design fitting our modern INLOOP-design.

Keep in mind that this is far from finished and needs many more improvements and changes.

<img width="1552" alt="bildschirmfoto 2018-12-03 um 18 23 09" src="https://user-images.githubusercontent.com/27271818/49390181-82cc9c00-f728-11e8-8b01-0ec6fb0aad87.png">

**Comment by PhilippMatthes** [comment]
@martinmo to calculate the hash, I would like to do it as follows:
1. Sort all file contents by corresponding file name (A...Z)
2. Concatenate all file contents directly together without any symbol in between

**Comment by PhilippMatthes** [comment]
@martinmo maybe it would be even better if I computed the hash in JS and then simply pass it with the other data to your REST endpoint.

**Comment by martinmo** [comment]
Looks good! I would suggest that we approach detailed styling issues and such things together in a pair programming session soon. Or in other words, do not spend too much time on styling *yet* ;-)

As for the hash calculation, that sounds solid but I doubt that sorting will work well. I would prefer to retain the order of the files as they appear on the screen, even if the user logs off. (I will keep the ordering in the database.)
