### ISSUE TITLE
JPlag check command might contain wrong parameter

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#280]
According to the [JPlag Github page](https://github.com/jplag/jplag), the `-m` parameter is defined as follows:
```
 -m <n>          (Matches) Number of matches that will be saved (default:20)
 -m <p>%         All matches with more than <p>% similarity will be saved.
```
This confuses me a bit. Currently, we format our args like this:
https://github.com/st-tu-dresden/inloop/blob/7f83410e681dfbaa4f7b1e445179b0e32037ee2e/inloop/grading/copypasta.py#L154

While, as I interpret it, it should actually be
```python
args += ["-m", "{}%".format(min_similarity)]
```
Please give feedback when you have time @martinmo, thanks!

**Comment by martinmo** [comment]
Good catch, can you please provide a fix?

Fortunately, we again check the similarity here: https://github.com/st-tu-dresden/inloop/blob/7f83410e681dfbaa4f7b1e445179b0e32037ee2e/inloop/grading/copypasta.py#L139

So, the consequence seems not to be too drastic and in favor of the students. Which means, in the worst case some rip-offs aren't detected which should have been detected :-)

For example, with the typical similarity value of 90 or 95 percent, the buggy code would lead JPlag to save 90 or 95 matches and the above line would then filter it.
