### ISSUE TITLE
Missing migration for task

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#292]
There is a migration missing in commit https://github.com/st-tu-dresden/inloop/commit/e3d24a0fc73ec132afdadb88eb14f859e1182ce7

it should be included into the migrations.

**Comment by martinmo** [comment]
Interesting, how is that possible? The release notes for [1.11.15](https://docs.djangoproject.com/en/2.2/releases/1.11.15/) and [1.11.16](https://docs.djangoproject.com/en/2.2/releases/1.11.16/) do not mention any migrations to be applied.

**Comment by martinmo** [comment]
The related commit was f91b100745aa579645c7a6b385ef11f2600615df (when the ordering config was added to the `Task` model).
