### ISSUE TITLE
Framework for Statistics

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#296]
After generating some amounts of data with the management command `generate_submissions` issued in Pull Request https://github.com/st-tu-dresden/inloop/pull/295, it became obvious that the current implementation of statistics is not optimal and should be refactored:
<img width="1552" alt="Bildschirmfoto 2019-07-29 um 16 41 28" src="https://user-images.githubusercontent.com/27271818/62057333-bca26380-b21f-11e9-9de0-8e3db243a207.png">
- The statistics take long time to load, since they are rendered synchronously
- As you can see, the lower left statistics are not very meaningful

The statistics should be implemented as a reusable framework to reduce the technical debt, so that:
- Every model admin view can be equipped with meaningful statistics, so that only few changes are needed
- Ideally, the framework gives a good interface to choose attributes from models to be tracked
- Optionally, the framework operates without external libraries, such as `Chart.js`
- The statistics should be rendered asynchronously

I already have good ideas and want to try them out, so I assign this issue to myself for now.

**Comment by martinmo** [comment]
Sounds good :+1: While you are at it, please decouple the data from the generated HTML. IIRC, the current solution embeds the data using a template inside a `<script>` tag. But it would be cleaner if the Javascript pulls data from a separate JSON endpoint.

**Comment by martinmo** [comment]
List of queries that should be supported:
- histogram of submitted solutions (passed, failed or both)
  - by category
- for one task, how many attempts, on average, are needed to pass the task

(maybe there are some more?)
