### ISSUE TITLE
Editor font size should be higher than 16px to avoid auto-zooming on iOS devices

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#304]
Unfortunately, Safari on iOS auto-zooms every `input` or `textarea`, including our code editor, which has a font size less than `16px`. This conducts a very bad UX on iOS devices. I propose raising the editor font size to `16px` to mitigate this issue. I already tested `16px` and did not experience problems with available space.

**Comment by martinmo** [comment]
1. Can you please provide a screenshot of the issue?
2. Is there maybe another way to fix this (such as the `<meta name="viewport">` headers)?

**Comment by PhilippMatthes** [comment]
Actually, I just checked on my iOS device and it does not autozoom. I originally thought that I'd run into this problem after I got it elsewhere. Will close this issue.
