### ISSUE TITLE
Raise PermissionDenied if user tries to download another user's solution

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#308]
Currently, the user gets a `404` when he accesses another user's solution archive. For consistency reasons, a `403` should be raised instead. **More importantly,** there should be a test case, which checks for solution archive download access.

**Comment by martinmo** [comment]
In the Django world you wouldn't do that, a `404` is perfectly fine. It doesn't leak information to outsiders that the object exists. This is done in all other place in our code base as well, e.g., if someone tries to access solution details of other persons without being an staff member. GitHub does this as well: open a private tab and try to access one of your personal repos (e.g., inloop-tasks) and you get a `404`.
