### ISSUE TITLE
SolutionEditorView post does not parse JSON correctly on Python 3.5

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#321]
https://github.com/st-tu-dresden/inloop/blob/76e0d573c02c23f7a0c1f7079cfc5bfec23d2784/inloop/solutions/views.py#L50-L55

This fails to read the JSON under Python 3.5, because the data is passed as a byte string, and the Python 3.5 `json.loads` does not load byte strings.

**Comment by martinmo** [comment]
Interesting, Python 3.6 and above added support for `bytes`/`bytearray`.
