### ISSUE TITLE
Conditional sticky tab bar overlaps <h1> heading

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#346]
When I, as a user, use an anchor link of the form `/tasks/example-task/#some-heading` on a task description page, the heading "Some Heading" is hidden by the tab bar. Links of this form can be obtained by clicking on the clip icon next to a heading (it appears during hovering):

![clip-icon](https://user-images.githubusercontent.com/1561982/75758377-4a08e180-5d34-11ea-8e73-09cea5ea6411.png)

**Steps to reproduce**:
1. Login as a normal user.
2. Go to a task page that contains headings and is longer than two screen pages (e.g., "Desktop Search Engine").
3. Click on one of clips next to the headings.

**Expected behavior**: it jumps to the heading, with the heading visible:

![Bildschirmfoto 2020-03-03 um 09 52 33](https://user-images.githubusercontent.com/1561982/75758703-bd125800-5d34-11ea-9d72-1928c724b36b.png)

**Actual behavior**: it jumps a bit too far and the heading isn't visible:

![Bildschirmfoto 2020-03-03 um 09 52 19](https://user-images.githubusercontent.com/1561982/75758759-c8fe1a00-5d34-11ea-88ab-2c084333c138.png)

**Comment by martinmo** [comment]
@PhilippMatthes, inspired by your `scroll-behavior` PR, last night I read some articles and watched videos about the newer `scroll-*` properties. I came across https://www.youtube.com/watch?v=pohyK8iz-SQ, where `scroll-margin` was mentioned in particular near the end (this video is part of a cool series by Mozilla designers, you should check out their channel).

After reading through https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin, I think it should be even easier to just use `scroll-margin-top: 65px` on the `h2` and `h3` elements, when the body has the `.autolink` class, instead of using pseudo elements and negative margins.

**Comment by PhilippMatthes** [comment]
Looks very promising! I will commit myself on this again and switch out the affected css if it works. 
Btw.: here is a screenshot from https://caniuse.com/#search=scroll-margin - it should be no compatibility problem. 

<img width="1269" alt="Bildschirmfoto 2020-03-06 um 09 03 24" src="https://user-images.githubusercontent.com/27271818/76064128-576ad980-5f89-11ea-86b1-8c77a168d81a.png">
